### ISSUE TITLE
Potential vulnerabilities in Puppet files: Use of HTTP without TLS

### ISSUE THREAD

**Issue by cantebigene** [ocf/puppet#1008]
26 configurations of HTTP without TLS were found in 14 different scripts.

Script 1: https://github.com/ocf/puppet/blob/b6af9ccf66097a963be216ce1230921478ec2d0c/modules/ocf_www/manifests/site/www.pp
 - Line [76](https://github.com/ocf/puppet/blob/b6af9ccf66097a963be216ce1230921478ec2d0c/modules/ocf_www/manifests/site/www.pp#L76): `^/(.*)$ http://lb.ocf.berkeley.edu:4080/$1 [p]`

Script 2: https://github.com/ocf/puppet/blob/b6af9ccf66097a963be216ce1230921478ec2d0c/modules/ocf/manifests/apt.pp
 - Line [17](https://github.com/ocf/puppet/blob/b6af9ccf66097a963be216ce1230921478ec2d0c/modules/ocf/manifests/apt.pp#L17): `http://mirrors/debian/`
 - Line [25](https://github.com/ocf/puppet/blob/b6af9ccf66097a963be216ce1230921478ec2d0c/modules/ocf/manifests/apt.pp#L25): `http://mirrors/debian/`
 - Line [33](https://github.com/ocf/puppet/blob/b6af9ccf66097a963be216ce1230921478ec2d0c/modules/ocf/manifests/apt.pp#L33): `http://mirrors/debian-security/`
 - Line [41](https://github.com/ocf/puppet/blob/b6af9ccf66097a963be216ce1230921478ec2d0c/modules/ocf/manifests/apt.pp#L41): `http://apt/`
 - Line [49](https://github.com/ocf/puppet/blob/b6af9ccf66097a963be216ce1230921478ec2d0c/modules/ocf/manifests/apt.pp#L49): `http://apt/`
 - Line [66](https://github.com/ocf/puppet/blob/b6af9ccf66097a963be216ce1230921478ec2d0c/modules/ocf/manifests/apt.pp#L66): `http://mirrors/debian/`
 - Line [72](https://github.com/ocf/puppet/blob/b6af9ccf66097a963be216ce1230921478ec2d0c/modules/ocf/manifests/apt.pp#L72): `http://mirrors/raspbian/raspbian/`
 - Line [80](https://github.com/ocf/puppet/blob/b6af9ccf66097a963be216ce1230921478ec2d0c/modules/ocf/manifests/apt.pp#L80): `http://archive.raspberrypi.org/debian/`
 - Line [91](https://github.com/ocf/puppet/blob/b6af9ccf66097a963be216ce1230921478ec2d0c/modules/ocf/manifests/apt.pp#L91): `http://mirrors/puppetlabs/apt/`

Script 3: https://github.com/ocf/puppet/blob/b6af9ccf66097a963be216ce1230921478ec2d0c/modules/ocf/manifests/packages/vscode/apt.pp
 - Line [10](https://github.com/ocf/puppet/blob/b6af9ccf66097a963be216ce1230921478ec2d0c/modules/ocf/manifests/packages/vscode/apt.pp#L10): `http://packages.microsoft.com/repos/vscode`

Script 4: https://github.com/ocf/puppet/blob/b6af9ccf66097a963be216ce1230921478ec2d0c/modules/ocf/manifests/packages/chrome/apt.pp
 - Line [21](https://github.com/ocf/puppet/blob/b6af9ccf66097a963be216ce1230921478ec2d0c/modules/ocf/manifests/packages/chrome/apt.pp#L21): `[arch=amd64] http://dl.google.com/linux/chrome/deb/`

Script 5: https://github.com/ocf/puppet/blob/b6af9ccf66097a963be216ce1230921478ec2d0c/modules/ocf_docker/manifests/init.pp
 - Line [49](https://github.com/ocf/puppet/blob/b6af9ccf66097a963be216ce1230921478ec2d0c/modules/ocf_docker/manifests/init.pp#L49): `http://docker-registry`

Script 6: https://github.com/ocf/puppet/blob/b6af9ccf66097a963be216ce1230921478ec2d0c/modules/ocf_jenkins/manifests/jenkins_apt.pp
 - Line [4](https://github.com/ocf/puppet/blob/b6af9ccf66097a963be216ce1230921478ec2d0c/modules/ocf_jenkins/manifests/jenkins_apt.pp#L4): `http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key`
 - Line [8](https://github.com/ocf/puppet/blob/b6af9ccf66097a963be216ce1230921478ec2d0c/modules/ocf_jenkins/manifests/jenkins_apt.pp#L8): `http://pkg.jenkins-ci.org/debian`

Script 7: https://github.com/ocf/puppet/blob/b6af9ccf66097a963be216ce1230921478ec2d0c/modules/ocf_jenkins/manifests/proxy.pp
 - Line [18](https://github.com/ocf/puppet/blob/b6af9ccf66097a963be216ce1230921478ec2d0c/modules/ocf_jenkins/manifests/proxy.pp#L18): `http://localhost:8080`
 - Line [19](https://github.com/ocf/puppet/blob/b6af9ccf66097a963be216ce1230921478ec2d0c/modules/ocf_jenkins/manifests/proxy.pp#L19): `http://localhost:8080 https://jenkins.ocf.berkeley.edu`

Script 8: https://github.com/ocf/puppet/blob/b6af9ccf66097a963be216ce1230921478ec2d0c/modules/ocf_puppet/manifests/puppetboard.pp
 - Line [27](https://github.com/ocf/puppet/blob/b6af9ccf66097a963be216ce1230921478ec2d0c/modules/ocf_puppet/manifests/puppetboard.pp#L27): `http://lb.ocf.berkeley.edu:4080`

Script 9: https://github.com/ocf/puppet/blob/b6af9ccf66097a963be216ce1230921478ec2d0c/modules/ocf_ssh/manifests/webssh.pp
 - Line [46](https://github.com/ocf/puppet/blob/b6af9ccf66097a963be216ce1230921478ec2d0c/modules/ocf_ssh/manifests/webssh.pp#L46): `http://webssh`

Script 10: https://github.com/ocf/puppet/blob/b6af9ccf66097a963be216ce1230921478ec2d0c/modules/ocf_prometheus/manifests/proxy.pp
 - Line [46](https://github.com/ocf/puppet/blob/b6af9ccf66097a963be216ce1230921478ec2d0c/modules/ocf_prometheus/manifests/proxy.pp#L46): `^/alertmanager(/.*)?$ http://127.0.0.1:9093/alertmanager$1 [p]`
 - Line [47](https://github.com/ocf/puppet/blob/b6af9ccf66097a963be216ce1230921478ec2d0c/modules/ocf_prometheus/manifests/proxy.pp#L47): `^/pushgateway(/.*)?$ http://127.0.0.1:9091$1 [p]`
 - Line [48](https://github.com/ocf/puppet/blob/b6af9ccf66097a963be216ce1230921478ec2d0c/modules/ocf_prometheus/manifests/proxy.pp#L48): `^/(.*)$ http://127.0.0.1:9090/$1 [p]`

Script 11: https://github.com/ocf/puppet/blob/b6af9ccf66097a963be216ce1230921478ec2d0c/modules/ocf_mirrors/manifests/monitoring.pp
 - Line [12](https://github.com/ocf/puppet/blob/b6af9ccf66097a963be216ce1230921478ec2d0c/modules/ocf_mirrors/manifests/monitoring.pp#L12): `http://mirrors.ocf.berkeley.edu`

Script 12: https://github.com/ocf/puppet/blob/b6af9ccf66097a963be216ce1230921478ec2d0c/modules/ocf_mirrors/manifests/init.pp
 - Line [141](https://github.com/ocf/puppet/blob/b6af9ccf66097a963be216ce1230921478ec2d0c/modules/ocf_mirrors/manifests/init.pp#L141): `http://mirrors.ocf.berkeley.edu/`

Script 13: https://github.com/ocf/puppet/blob/b6af9ccf66097a963be216ce1230921478ec2d0c/modules/ocf_csgo/manifests/init.pp
 - Line [35](https://github.com/ocf/puppet/blob/b6af9ccf66097a963be216ce1230921478ec2d0c/modules/ocf_csgo/manifests/init.pp#L35): `curl http://media.steampowered.com/installer/steamcmd_linux.tar.gz | tar xzf - -c /opt/csgo/bin`

Script 14: https://github.com/ocf/puppet/blob/b6af9ccf66097a963be216ce1230921478ec2d0c/modules/ocf_irc/manifests/webirc.pp
 - Line [23](https://github.com/ocf/puppet/blob/b6af9ccf66097a963be216ce1230921478ec2d0c/modules/ocf_irc/manifests/webirc.pp#L23): `http://lb.ocf.berkeley.edu:4080`

This type of smell can lead to a well-known type of vulnerability, as documented by CWE ([CWE-546](https://cwe.mitre.org/data/definitions/546.html)). Using HTTP without TLS to communicate with other servers/sources gives access to sensitive or security-critical data in cleartext to unauthorized actors during network communication/traffic (e.g., man-in-the-middle attacks).

Configuring HTTP without using TLS in **Puppet** configuration files is considered to be a security smell (cf. [[icse20](https://dl.acm.org/doi/pdf/10.1109/ICSE.2019.00033)]).

**Recommendation**
You can instead use HTTPS (HTTP using TLS) to protect the privacy and integrity of the exchanged data. For instance, replace `$auth_url = ‘http://127.0.0.1:35357/’` by `$auth_url = ‘https://127.0.0.1:35357/’`. Thus, you will highly decrease the chances of having your app data leaked.

**Comment by chriskuehl** [comment]
@cantebigene we appreciate the attempt but these are spam, please stop filing these.
