### ISSUE TITLE
Upgrading desktops to Debian 11

### ISSUE THREAD

**Issue by singingtelegram** [ocf/puppet#1139]
Changes in Debian 11:

- [x] security repo renamed to bullseye-security (vs. bullseye/updates)
- [ ] Python 2 is deprecated, there are a bunch of py2 packages in extrapackages
- [x] <del>No i386 packages on our mirrors</del>
- [x] Zenmap and florence are removed
  - is there a replacement frontend for Nmap?

Issues with current bullseye desktops:
- [ ] Xfce theme takes a while to apply after logging in
- [ ] Missing icons in thunar?
- [x] page indicator not working (fixed in #1148)
- [ ] /usr/bin/sshfs gets deleted every reboot??? needs triage
- [x] blender installation issues
- [x] xvnc4viewer deprecated
(fixed in #1148)
- [ ] MS repo doesn't have powershell for Debian 11
- [x] login icon missing (should be fixed in #1148)
- [ ] I think we still need Java 8 for legacy applications (javaws?)

And perhaps many more...

**Comment by ethanhs** [comment]
>  No more support for i386

note that this is technically due to our mirrors not having i386. If we have packages that are i386 only then we can add this back

**Comment by singingtelegram** [comment]
- [ ] blender installation issues
- [ ] xvnc4viewer deprecated

**Comment by singingtelegram** [comment]
Support for non-GLVND OpenGL and EGL libraries on Linux

The release 430 series will be the last to support installing Linux OpenGL and EGL client libraries that do not use the GL Vendor Neutral Dispatch (GLVND) loader library.

https://github.com/ocf/puppet/issues/1139

As a result, the libgl1-nvidia-glx package is no longer present in bullseye (460)

**Comment by ethanhs** [comment]
I can test steam at some point.


We should remove `python-*` from extrapackages anyway, as Python 2 is dead.

**Comment by nikhiljha** [comment]
All desktops are now on bullseye 🥳
