### ISSUE TITLE
Drop tanglu and tanglu-releases 

### ISSUE THREAD

**Issue by singingtelegram** [ocf/puppet#1152]
prev RT: #915

The Tanglu project has been discontinued for over 4 years now (website defunct), and it's been more than one year since we published the notice on http://mirrors.ocf.berkeley.edu/tanglu/.

I check the access logs and noticed very little activity, and a quick grep/awk query showed no client request for .gz or .deb files.

The tanglu and tangly-releases folders currently occupy ~500GB + 65.7GiB of disk space on fallingrocks. Fallingrocks is running low on disk space with only ~550GB available, so it would be beneficial if we move or remove tanglu from our mirrors.

**Comment by ethanhs** [comment]
Yeah we should delete this, as 500GB would give us a lot more breathing room for mirrors.
