### ISSUE TITLE
Update element-desktop apt configuration

### ISSUE THREAD

**Issue by ethanhs** [ocf/puppet#1154]
When running apt update on the desktops it seems that element has changed its apt key or something. This has caused a bit of puppet spam, and we should fix it.

The apt info appears to be here (if you click "linux"): https://element.io/get-started

**Comment by reedjones** [comment]
this is fixed https://github.com/ocf/puppet/commit/fafd3716e69db894444c00076d4d9a89bb0ca8b8

**Comment by ethanhs** [comment]
Awesome!
