### ISSUE TITLE
Debian 11 and NIC interface names

### ISSUE THREAD

**Issue by singingtelegram** [ocf/puppet#1156]
https://wiki.debian.org/NetworkInterfaceNames#THE_.22PREDICTABLE_NAMES.22_SCHEME

https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/

https://github.com/ocf/puppet/blob/0b79abe73827ae3122fc3fffe3ecd07340ad7a88/modules/ocf_desktop/files/suspend/ocf-suspend

Currently eth0 is hardcoded in the ocf-suspend script.

**Comment by ethanwu10** [comment]
Fixed by #1157
