### ISSUE TITLE
Investigate Docker repo

### ISSUE THREAD

**Issue by matthew-mcallister** [ocf/puppet#182]
It seems like apt.dockerproject.org hasn't updated since May 5 even though it was getting monthly updates before. We might consider switching to download.docker.com, [which is apparently the official source now](https://docs.docker.com/engine/installation/linux/docker-ce/debian/).

**Comment by jvperrin** [comment]
The docker package changed name too, so we need to update that from `docker-engine` to `docker-ce` wherever it is referenced.

**Comment by chriskuehl** [comment]
ffs, how many times are they going to rename the docker package?

`lxc-docker` => `docker.io` => `docker-engine` => `docker-ce`

**Comment by jvperrin** [comment]
This is resolved by #183.
