### ISSUE TITLE
/etc/sudoers is broken if staffvm and no owner

### ISSUE THREAD

**Issue by jvperrin** [ocf/puppet#298]
The `/etc/sudoers` file becomes broken if the hiera file to add an owner is not added quickly enough, since it contains the following line (notice the single space at the front):

```
 ALL=(ALL) NOPASSWD: ALL
```

This appears to be because the [hiera lookup for an owner](https://github.com/ocf/puppet/blob/c4a9b1c6b9041297fa64ac418bb53b2cec99fcc2/hieradata/type/staffvm.yaml#L3) returns an empty string in the `usudo` array, leading to a line being added in the [`/etc/sudoers` template](https://github.com/ocf/puppet/blob/master/modules/ocf/templates/sudoers.erb), but not one with an actual user. Probably should just filter out empty or invalid users in the [`auth.pp` manifest](https://github.com/ocf/puppet/blob/master/modules/ocf/manifests/auth.pp)?

**Comment by jvperrin** [comment]
Same happens with `/etc/security/access.conf`, although it's not as bad to have it happen there, since it doesn't need a login as root to fix it.

**Comment by chriskuehl** [comment]
Could we make puppet fail hard if there's no owner instead? That seems better to me (force someone to fix it) rather than trying to hobble along and handle this error everywhere we use the owner.

**Comment by jvperrin** [comment]
Yeah, that would be reasonable, every staff VM should have an owner, so we could just error if we find any that don't have a current owner.
