### ISSUE TITLE
Get rid of puppet reports when environment changes

### ISSUE THREAD

**Issue by matthew-mcallister** [ocf/puppet#31]
This has something to do with tagmail config, according to Dara.

**Comment by jvperrin** [comment]
This sounds like a good idea to me, my concern would be if an environment was left not set as production on a machine then it could be a while before it was discovered. That's still the case now, but the emails help a little bit with that. I think the best way to fix this would probably be to have a script that checks the status of all the environments and warns us if one has not been set back to production. Thoughts?

**Comment by jvperrin** [comment]
`tagmail.conf` has the single line

    warning, err, alert, emerg, crit: puppet

on the puppetmaster. Should warning just be removed from that list then? I feel like we want to get warnings, as long as they aren't about changing environments.

**Comment by matthew-mcallister** [comment]
That sounds like a better solution and could possibly be integrated into ldap-lint.

The idea behind this change is to be one step closer to spam-free puppet. These emails admittedly wouldn't be nearly as bad if we had already cut down on the noise from other sources. All the same, changing environments is a very common occurrence and is basically always expected, which is why an explicit email alert each time is unnecessary.

**Comment by matthew-mcallister** [comment]
I tried looking up which types of messages go into which log levels, but didn't find anything with just a quick search. We probably don't want to disable all warnings; hopefully there's a more fine-grained way to disable these alerts.

**Comment by chriskuehl** [comment]
This was actually changed to log level notice in newer Puppet versions:
https://github.com/puppetlabs/puppet/commit/42f7de3f2213c7bef7a8988e9b8684e281d8380d

So maybe the solution is just try to upgrade Puppet. That has other benefits as well.

**Comment by daradib** [comment]
tagmail requires a separate [puppetlabs-tagmail](https://github.com/puppetlabs/puppetlabs-tagmail) module in Puppet 4+.

Another approach is to get rid of tagmail and deal with reports some other way. For example, you can store them as yaml files for periodic processing with a python script. Perhaps such a tool already exists. Advantage is that you can aggregate errors from different servers into one email. See [Puppet Reporting](https://docs.puppetlabs.com/puppet/latest/reference/reporting_about.html). I was too lazy to do this when setting up puppet, hence tagmail.
