### ISSUE TITLE
Retry obtaining certs if domains don't match

### ISSUE THREAD

**Issue by jvperrin** [ocf/puppet#343]
One problem right now with the Let's Encrypt changes (in #337) is that if new domains are added in LDAP, they likely won't be in DNS yet, a request will be made for a new cert, it'll fail, and won't be retried, since it's been [refreshed once](https://github.com/ocf/puppet/blob/06b9244683d6396a053aa9dc0b25e42b37f27491/modules/ocf/manifests/ssl/lets_encrypt/dns.pp#L27) and that's it.

If the domains requested don't match the cert, or maybe if the previous cert request failed, we should retry the cert request, since giving up isn't a good option. I'm not sure what would be the best option here, one quick and dirty trick that comes to mind is to make a lockfile of sorts, so that if the cert fails to get obtained, a future run can check if the file exists, and schedule a run. I'd hope there's something cleaner than this, maybe a custom fact that shows the domains in each cert by parsing `openssl x509 -in cert.pem -text` output?

**Comment by kpengboy** [comment]
We already have a hack which checks if the current cert will expire soon. Can we generalize this to check if the domain list is correct, etc.?
