### ISSUE TITLE
ocfbroker group exists on the desktops

### ISSUE THREAD

**Issue by abizer** [ocf/puppet#362]
seems like this shouldn't be the case:

```bash
abizer@blackout:~$ check abizer
abizer:*:35934:1000:Abizer Lokhandwala:/home/a/ab/abizer:/bin/zsh
Created on: 2015-10-03
Member of group(s): ocfbroker ocfstaff ocfroot ocfdev ocfofficers
```

**Comment by kpengboy** [comment]
@abizer the ocfbroker group should exist on desktops, shouldn't it?

But a more problematic issue that `ocfbroker` should be a system user
(`system => true`) but isn't:

https://github.com/ocf/puppet/blob/100faf715810823124b3510c5f18c3baa4b1d6fa/modules/ocf_desktop/manifests/printnotify.pp#L2-L5

This causes the `ocfbroker` user to be assigned some random UID that
actually collides with some member's UID. The `ocfbroker` group also has an
inappropriately high UID.
