### ISSUE TITLE
Box.com deprecating WebDAV

### ISSUE THREAD

**Issue by keur** [ocf/puppet#398]
Box.com has announced that they are [deprecating WebDAV support](https://community.box.com/t5/Box-Product-News/Deprecation-WebDAV-Support/ba-p/55684) on January 31st, 2019. Indiana University has a nice page on [alternative ways to connect to Box.com](https://uisapp2.iu.edu/confluence-prd/display/SOICKB/Using+Box+under+Linux). I'm thinking that connecting to box over the `FTPS` protocol will be the best replacement of those listed.

**Comment by jvperrin** [comment]
This seems like a duplicate of #367, although using FTPS is a bit different (compared to rclone or something like that).
