### ISSUE TITLE
Upgrade remaining machines from jessie to stretch

### ISSUE THREAD

**Issue by glee-** [ocf/puppet#405]
2018-10-23 03:13:07 -0700 //death.ocf.berkeley.edu/Facter (err): error while processing "/opt/puppetlabs/puppet/cache/facts.d/iface-linked" for external facts: child process returned non-zero exit status (1).

File in question is here: puppet/modules/ocf/facts.d/iface-linked on line 8
      
death, tsunami, and werewolves are the remaining machines currently on jessie. We should tie up the loose ends here before transitioning to buster.

**Comment by abizer** [comment]
only ~3 months to the buster soft freeze

@jvperrin has put a lot of work into getting us ready to moving away from Jessie, right now we just need to migrate users from werewolves to vampires, and otherwise, tsunami and death should be good to go to upgrading to stretch.

**Comment by abizer** [comment]
discourse thread for other context: https://leprosy.ocf.berkeley.edu/forum/t/debian-buster-ocf/71

**Comment by abizer** [comment]
@jvperrin has finished migrating all the apphosts from werewolves to vampires, with the exception of calhacks. this should be ready to resolve by tomorrow, hopefully.

**Comment by abizer** [comment]
[This is done!](https://status.ocf.berkeley.edu/2018/11/upgrading-user-facing-servers-to-debian.html)
