### ISSUE TITLE
ensure all kubernetes files go in /etc/kubernetes-ocf

### ISSUE THREAD

**Issue by kkuehlz** [ocf/puppet#439]
i stupidly put some kubernetes files in /etc/kubernetes. this is managed by kubeadm... so far it's been fine, but it's better to take these files out of there.

**Comment by abizer** [comment]
preferably we'd namespace everything as starting with ocf rather than ending, e.g. `/etc/ocf-kubernetes` so it all sorts near one another in `ls`
