### ISSUE TITLE
sg.ocf.io cert is broken

### ISSUE THREAD

**Issue by abizer** [ocf/puppet#464]
@jvperrin mentioned this some time ago but I thought I'd make a ticket for it

**Comment by jvperrin** [comment]
This also applies for grafana.ocf.io, static.ocf.io, templates.ocf.io, rt.ocf.io, etc.

Anything hosted directly by marathon (using the lb cname) isn't available over a .io domain.

**Comment by jvperrin** [comment]
Ok, #468 didn't fully solve this, since the redirect on lb doesn't listen on SSL. Should be a reasonably easy fix though.
