### ISSUE TITLE
Fix docker socket group override

### ISSUE THREAD

**Issue by kpengboy** [ocf/puppet#479]
We currently set the Docker socket group by [adding a systemd override for `docker.socket`](https://github.com/ocf/puppet/blob/c63c4e414fdde3780d5204dce639f175e203ec83/modules/ocf/manifests/packages/docker.pp#L39-L44), but it seems that lately dockerd no longer uses systemd to manage its socket. Hence, our override needs to be updated.

The way to go is probably to override the `docker.service` command to pass the `-G` flag with the appropriate group. (Unless someone knows of a better way.)

**Comment by redplanks** [comment]
This was fixed by upgrading `docker-ce` to 18.09.1; apparently `docker.socket` [needed to be added back](https://github.com/docker/docker-ce-packaging/pull/276) as a requirement for `docker.service`.
