### ISSUE TITLE
add hsts to death/www

### ISSUE THREAD

**Issue by gnowxilef** [ocf/puppet#49]
https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security

probably also includesubdomains and preload.

**Comment by chriskuehl** [comment]
We already do HSTS on www. We can't do `includeSubDomains` as not all of `*.ocf.berkeley.edu` can have HTTPS (e.g. `*.apphost.o.b.e` and other special cases -- though I think all of our regular domains, even the unimportant stuff like munin, is indeed https now).

Preload is not an option sadly as they won't let you register subdomains (ocf.b.e). We did update the rules for the EFF's HTTPS Everywhere extension, though: https://github.com/EFForg/https-everywhere/pull/1459
