### ISSUE TITLE
lets-encrypt-update silently failing

### ISSUE THREAD

**Issue by abizer** [ocf/puppet#491]
for some reason the lets-encrypt-update script we use to acquire new and updated certs for death has been silently failing to run for some time (rt#7937, rt#7901, etc.) 

there's nothing relevant in the logs, as far as I can tell, and we aren't getting any cron emails from failures, so perhaps there might be some way for us to turn up the verbosity / have it report everything for a bit to see if we can trigger a failure?

**Comment by abizer** [comment]
so far this issue hasn't resurfaced

**Comment by jvperrin** [comment]
I'm going to close this as we haven't seen this happen in many months now.
