### ISSUE TITLE
mirrors: use optimized syncing script for more frequent updates

### ISSUE THREAD

**Issue by dkess** [ocf/puppet#507]
For most of our mirrors, we use a simply `rsync` command to sync with upstream mirrors. This compares every file, which is inefficient. Arch Linux recommends that mirrors use an [optimized script](https://git.server-speed.net/users/flo/bin/tree/syncrepo.sh) that initially only checks the last updated timestamp. If it isn't new enough, it avoids running a full sync.

If we use this script, we would be allowed to sync at frequencies higher than one hour. In this way our Arch Linux mirrors can be ｂｌｅｅｄｉｎｇ ｅｄｇｅ.

**Comment by BernardZhao** [comment]
I think this can be closed?

**Comment by abizer** [comment]
ｈｉｔ ｔｈａｔ ｍｏｔｈｅｒｆｕｃｋｉｎｇ ｃｌｏｓｅ ｂｕｔｔｏｎ
