### ISSUE TITLE
Puppet Kubernetes user roles

### ISSUE THREAD

**Issue by dkess** [ocf/puppet#543]
We want to give `read` permission to everyone on `ocfstaff` and `cluster-admin` to everyone on `ocfroot`. We've already made these resources, but they should be stored in the Puppet repo and applied.

**Comment by fydai** [comment]
Done here https://github.com/ocf/puppet/commit/97d273cde1e5517da037f5ed16eeaf977ed18756#diff-56a99fe4d0ad0425988fb77b4a3fd726
