### ISSUE TITLE
ocf_mesos: add authentication for zookeeper

### ISSUE THREAD

**Issue by chriskuehl** [ocf/puppet#61]

**Comment by chriskuehl** [comment]
a907e38b9dc4d27975481f8083ae7f455fde0c1a gets mesos slaves and masters using auth

Still to do:
* Marathon when connecting to Zookeeper to talk to the Mesos master
* Marathon when connecting to Zookeeper for its own state
* mesos-dns

**Comment by jvperrin** [comment]
Closing, as mesos/marathon/zookeeper have been removed in favor of kubernetes/etcd (#680).
