### ISSUE TITLE
Package info locations

### ISSUE THREAD

**Issue by MCer4294967296** [ocf/puppet#623]
#620 I put a package in ocf::packages, and was pointed out that this should be put into ocf_desktop::packages. However, packages like chrome and brave and vscode, which are also only installed on desktops, is put in ocf::packages::. I do realize that brave/chrome/vscode need additional apt entry, but other than that, do we have any explanation regarding the difference?

**Comment by abizer** [comment]
`ocf::packages` gets installed on all machines
`ocf::extrapackages` gets installed on user-facing machines only
`ocf_desktop::packages` gets installed on the desktops only, so applications that require X11

there are things in `ocf::packages::<package>.pp`, and those are all times where we need to do some kind of special case behavior for something - they're required individually in the appropriate service-level module, e.g. `ocf::packages::brave` is only included by `ocf_desktop::init`

**Comment by MCer4294967296** [comment]
I see. So the fact that chrome needs an apt entry exceeds the fact that chrome is installed only on desktops in terms of special-ness.

**Comment by MCer4294967296** [comment]
Sounds like the .NET stuff will be in `ocf::packages` and osu will be packaged into our internal apt and then show up in `ocf_desktop::`

**Comment by ethanhs** [comment]
I would say since OSU is the reason .NET is being installed, it should be in at least `extrapackages` (e.g. we don't need it on corruption). But I have a preference for it being in `ocf_desktop`.
