### ISSUE TITLE
use mail: attribute address for sending to staff@

### ISSUE THREAD

**Issue by abizer** [ocf/puppet#637]
in #575, we changed the posting rules to staff@ to be staff only, where the addresses allowed to send are given by the usernames in the ocfstaff LDAP group with '@ocf.berkeley.edu' appended. This will only easily allow staff with GApps accounts to reply to these restricted posting addresses. Instead, the allowed list should use the email addresses from the mail: attribute in ldap for members of the ocfstaff group. This will allow members to reply from the address that they received the email at.

**Comment by cg505** [comment]
We should use the union of the two (for each person, include username@ocf.berkeley.edu and also whatever is in LDAP under the mail attirubte).

**Comment by abizer** [comment]
+ @g.ocf.berkeley.edu

**Comment by abizer** [comment]
yeah that sounds good. anthrax should also already have the keytab necessary to pull the mail attribute, I'll look into this if I have some time

**Comment by abizer** [comment]
closed via #708
