### ISSUE TITLE
keyserver: Replace sks with Hagrid/sequoia

### ISSUE THREAD

**Issue by abizer** [ocf/puppet#719]
sks is unmaintained and vulnerable, and not well designed. keys.openpgp.org is running Hagrid, which is a new validating keyserver that's supposed to be better than sks. We should consider running an instance ourselves to replace our existing sks-based pgp.ocf.berkeley.edu

**Comment by nikhiljha** [comment]
pgp.ocf.berkeley.edu is now gone, so this can be closed
