### ISSUE TITLE
Show scanner icon on desktops with scanners

### ISSUE THREAD

**Issue by cg505** [ocf/puppet#743]
https://github.com/ocf/puppet/blob/34f75e80e1b1475e099e5f1fa189a753001113fc/modules/ocf_desktop/files/xsession/Xsession#L15 has a bug. `grep - v` is misused: this will return 0 as long as there are any lines that don't match the regex (as opposed to returning 0 when _no lines_ match the regex). To fix, we can just change this to `! lsusb | grep -qE '(Fujitsu|CanoScan|Canon, Inc)'`.

**Comment by jvperrin** [comment]
Heh, my bad on that one
