### ISSUE TITLE
kubeadm tokens expire

### ISSUE THREAD

**Issue by cg505** [ocf/puppet#801]
we should set `kubernetes::ttl_duration` to 0. See https://github.com/puppetlabs/puppetlabs-kubernetes/blob/e9d2132fc716a600c268edbc6473825df1712df2/manifests/config/kubeadm.pp#L27

Also, when `/etc/kubernetes/config.yaml` is updated, `kubeadm` is not run. In this case, we need to run `kubeadm token create --config /etc/kubernetes/config.yaml` (I don't think puppet will run this).

**Comment by cg505** [comment]
Note: as long as this is unfixed, you need to run the `kubeadm token create...` command before adding any new kubernetes nodse

**Comment by nikhiljha** [comment]
we no longer use kubeadm in new kubernetes
