### ISSUE TITLE
Add HAProxy healthchecks to lb

### ISSUE THREAD

**Issue by cg505** [ocf/puppet#802]
HAProxy supports [healthchecks for backend servers](https://www.haproxy.com/documentation/aloha/10-0/traffic-management/lb-layer7/health-checks/). We should use these to avoid routing traffic from lb to kubernetes workers that might be down.

**Comment by ja5087** [comment]
Best way is probably to query worker:10256/healthz

**Comment by cg505** [comment]
I'm not sure, seems like we should just be hitting worker:31234 directly, since this is the path that is actually used. We could envision some issue where the NodePort isn't working on one worker but the kube healthz is still ok

**Comment by ja5087** [comment]
Makes sense. It seems that `ingress-nginx` also has it's own healthz endpoint: https://kubernetes.github.io/ingress-nginx/user-guide/default-backend/
