### ISSUE TITLE
Backup kubernetes

### ISSUE THREAD

**Issue by fydai** [ocf/puppet#852]
Currently, we do not backup the state of our kubernetes cluster. Our current backup configuration is located here (https://github.com/ocf/puppet/blob/master/modules/ocf_backups/files/rsnapshot.conf).

We should make a backup-kubernetes script here (https://github.com/ocf/puppet/tree/master/modules/ocf_backups/files) which saves the certificates of our kubernetes cluster as well as everything in etcd, so we can recover the state of our kubernetes cluster if necessary.

**Comment by abizer** [comment]
@kpengboy can attest that the event that motivated the creation of this issue is also the reason for the creation of github.com/ocf/services

**Comment by cg505** [comment]
something something ~staff/legends

**Comment by nikhiljha** [comment]
now tracked in https://github.com/ocf/kubernetes/issues/35
