### ISSUE TITLE
Write proper buster config for ocftv

### ISSUE THREAD

**Issue by encadyma** [ocf/puppet#887]
@fydai and I worked on this one night when ocf-tv was moved to buster.
A list of changes we could come up with:

- [x] remove nodm dependency (nodm is deprecated)
- [x] add lightdm
- [ ] create group name autologin, add ocftv to group
- [x] install mpd + mpc
- [x] make mpd listen to anything (change mpd.conf)
- [ ] make sure x11 vnc service starts after (not before) lightdm
- [x] solve volume problems on mpd in some way (UPDATE: use pulseaudio sink, see mpd.conf)
- [ ] change ocf-tv script to remove hardcoded sink value

lightdm.conf:
```
[Seat:*]
pam-service=lightdm
pam-autologin-service=lightdm-autologin
autologin-user=ocftv
autologin-user-timeout=0
session-wrapper=/etc/X11/Xsession
greeter-session=lightdm-greeter
```

**Comment by cg505** [comment]
not sure this should be closed... there may still be a few buster things on tornado?

**Comment by encadyma** [comment]
I plan on reopening if any issues arise once we can get back to lab and get a chance to test out the Puppet config on tornado, though I think this covers a majority of it
