### ISSUE TITLE
Get http://rt/ to work from inside the lab

### ISSUE THREAD

**Issue by kpengboy** [ocf/puppet#92]
Right now that URL redirects to fluffy (instead of RT as it used to) because the nginx running on marathon-lb doesn't understand vhost aliases or something like that. We should fix that.

**Comment by chriskuehl** [comment]
are you planning to do this? if not i can

**Comment by kpengboy** [comment]
My queue of todos is quite long as of now.

**Comment by chriskuehl** [comment]
i'll take that as a no

**Comment by chriskuehl** [comment]
should be fixed in 8755832ceb096f12515d7ad88d3075f91407fa65
