### ISSUE TITLE
Upgrade HPC to buster

### ISSUE THREAD

**Issue by redplanks** [ocf/puppet#940]
There shouldn't be too many issues with the setup breaking. Some users' libraries might break, but if we warn them beforehand it should be okay.

Plus, newer versions of scientific computing packages would be good to have, instead of relying on really old stretch/spotty stretch-backports ones.

**Comment by ja5087** [comment]
This will be really nice since people have been requesting newer CUDA and it will let us use a version of slurm that's almost half a decade newer.

**Comment by ja5087** [comment]
done
